### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by bnowacki** [zuzannapajak/DatabaseProgramming#1]
Design and implement a database system. Note the following guidelines:

Grade 3

- [x] At least 5 tables should be defined. @zuzannapajak 
- [x] The database schema reflects all the attributes and dependencies of “real” objects within the given topic.
- [x] There are relationships between tables based on primary and foreign keys.
- [x] Sample data are provided for all the tables. @bnowacki 
- [x] At least 10 SQL queries for data preview should be defined; aggregate functions and SQL clauses should be considered. @KMuszynski 
- [x] At least 3 procedures performing different operations should be defined (e.g., for adding, modifying, and retrieving data from the database). @smarciniak 
    - [x] 1
    - [x] 2
    - [x] 3
- [x] Functions that enable calculations should be defined (at least 2). @tymek
    - [x] 1
    - [x] 2 

Grade 4

- [x] Definitions of procedures and functions should prove your high database skills (complexity, "if" statements, loops, cursors, exception handling...) and should differ in data they work on, operations they perform, and attributes they take. 

Grade 5

- [x] At least 3 tables should have triggers defined. @bnowacki 
- [x] Additional database structures should be defined, e.g., a package. @wojmok
